# Generated by Django 6.0.3 on 2026-03-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('islamabad', 'Islamabad'), ('lahore', 'Lahore'), ('karachi', 'Karachi'), ('peshawar', 'Peshawar'), ('quetta', 'Quetta'), ('multan', 'Multan'), ('sargodha', 'Sargodha'), ('hyderabad', 'Hyderabad'), ('rawalpindi', 'Rawalpindi'), ('sialkot', 'Sialkot'), ('mardan', 'Mardan')], default='none', max_length=100),
            preserve_default=False,
        ),
    ]
