# Generated by Django 6.0.3 on 2026-04-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('paid', 'paid'), ('unpaid', 'unpaid')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid')], default=('paid', 'paid'), max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('shipped', 'shipped'), ('Delivered', 'delivered')], default=('pending', 'pending'), max_length=10),
        ),
    ]
