# Generated by Django 6.0.3 on 2026-04-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='medicine',
            new_name='medicines',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'cash'), ('card', 'card'), ('online', 'online')], max_length=10),
        ),
    ]
