# Generated by Django 6.0.3 on 2026-04-06 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_medicine_order_medicines_and_more'),
        ('products', '0002_alter_medicine_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='medicines',
            new_name='medicine',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CA', 'Cash'), ('CR', 'Card'), ('ONL', 'Online')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PA', 'Paid'), ('UP', 'Unpaid')], default='UP', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('SH', 'Shipped'), ('DEL', 'Delivered')], default='PD', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='products.medicine'),
        ),
    ]
