# Generated by Django 6.0.3 on 2026-03-31 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_customer'),
        ('products', '0016_rename_medicine_name_medicine_name_medicine_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profit',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='medicine',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='products.medicine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='profit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='OrderedItem',
        ),
        migrations.DeleteModel(
            name='Profit',
        ),
    ]
