# Generated by Django 6.0.3 on 2026-03-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
