# Generated by Django 6.0.3 on 2026-03-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='profit',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='medicine',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='profit',
        ),
        migrations.DeleteModel(
            name='OrderedItem',
        ),
    ]
