# Generated by Django 6.0.3 on 2026-03-30 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_order_customer_remove_ordereditem_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.medicine'),
        ),
    ]
