# Generated by Django 6.0.3 on 2026-03-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_stock_medicine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='medicine_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='medicine',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='stock',
        ),
    ]
