# Generated by Django 6.0.3 on 2026-04-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_rename_medicine_name_medicine_name_medicine_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
